options:
  volume-backend-name:
    type: string
    default:
    description: |
      Volume backend name for the backend. The default value is the
      application name in the Juju model.
  use-multipath:
    type: boolean
    default: True
    description: |
      Whether to use a multipath connection for iSCSI or FC in Cinder
      volume service. Enabling multipath for VMs is managed by the
      "use-multipath" option in the nova-compute charm.
  protocol:
    type: string
    default:
    description: |
      SAN protocol to use. Choose between iscsi or fc.
  product:
    type: string
    default:
    description: |
      Type of a storage product. Possible values are 'V3', 'V5',
      '18000', or 'Dorado'.
  rest-url:
    type: string
    default:
    description: |
      Semicolon(;) separated list of the REST interface. e.g.,
      https://my-endpoint.example.com:8088/deviceManager/rest/
  username:
    type: string
    default:
    description: |
      User name of a storage administrator.
  password:
    type: string
    default:
    description: |
      Password of a storage administrator.
  storage-pool:
    type: string
    default:
    description: |
      Semicolon(;) separated list of storage pools to be used.
